config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'


  resources :users
  resources :clubs#, only: [:index, :show, :new]

  resources :users do
    resources :clubs
  end
  
  resources :clubs do
    resources :club_users
  end
  # http://127.0.0.1:3000/clubs/1/club_users/new

  resources :users do
    resources :club_users
  end
  # resources :users do
  #   resources :club_users, shallow: true ##shallow: true routing to avoid deep nesting
  # end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :user #person who created it
  has_many :club_users, :dependent => :destroy

  has_one_attached :logo
  has_many :users, through: :club_users, :dependent => :destroy #Those who joined
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :date_founded, presence: true
  validates :summary, presence: true
  validate :date_founded_cannot_be_in_the_future
  validates :description, length: { minimum: 10 }

  scope :alphabeticallize, -> { order(:name) }

  def date_founded_cannot_be_in_the_future
    if date_founded.present? && date_founded > Date.today
      errors.add(:date_founded, "Cannot be in the future")
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    @club.user_id = session[:user_id]
    if @club.save
      @club_user = current_user.club_users.build(club_id: @club.id, admin: true, reason: "Club Founder")
      @club_user.save
      redirect_to club_path(@club.id)
    else
      flash[:error] = @club.errors.full_messages
      render :new
    end
  end

  def show
    @current_user = current_user
    @club = Club.find_by_id(params[:id])
    @club_user_user = ClubUser.find_by(club_id: @club.id, user_id: current_user.id)
    @club_users = ClubUser.where(club_id: @club.id)
    # byebug
    redirect_to "/clubs/new" if !@club
  end

  def index
    if params[:user_id] && @user = User.find_by(id: params[:user_id])
      @clubs = @user.clubs
    else
      @clubs = Club.all.alphabeticallize
    end
  end

  def edit
    @club = Club.find_by_id(params[:id])
    @club_users = ClubUser.where(club_id: @club.id)
  end

  def update
    @club = Club.find_by(id: params[:id])
    @club_users = ClubUser.where(club_id: @club.id)
    @club.update(club_params)
    if @club.valid?
      redirect_to club_path(@club)
    else
      render :edit
    end
  end

  def destroy
    @club = Club.find_by_id(params[:id])
    @club.destroy
    redirect_to user_path(current_user)
  end

  private

  def club_params
    params.require(:club).permit(:name, :description, :date_founded, :summary, :logo)
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
  def show_index_title_conditionally
    if @user
      content_tag(:h1, "Here are all of #{@user.name}'s clubs:")
    else
      content_tag(:h1, "Here are all existing clubs:")
    end
  end
end

app/views/clubs/edit.html.erb
<h1>Update this Club</h1>
<%= render partial: 'layouts/errors', locals: {obj: @club} %>
<%#= render partial: 'layouts/errors', locals: {obj: @club_users} %>
<%= form_for(@club) do |f| %>
  <div class="form-group">
    <label for="club_name"> Club Name</label>
    <%= f.text_field :name, class:"form-control"%>
    <br>
    <label for="club_summary"> In 1 to two sentences, what is the purpose of your club? </label>
    <%= f.text_field :summary, class:"form-control"%>
    <br>
    <label for="club_desctription">In more words, explain how your club came abuut and how it functions</label>
    <%= f.text_area :description, class:"form-control"%>
    <br>
    <label for="club_date_founded">Date Founded</label>
    <%= f.date_field :date_founded, class:"form-control"%>
    <br>
    <label for="club_logo">Upload Club Logo</label> <br>
    <%= f.file_field :logo %>
    <br>
    <br>
    <%= f.submit "Update Club Info", class: "btn btn-primary btn-lg"%>
  </div>
<% end %>
<% if current_user.id  == @club.user_id  %>
  <%= button_to "Delete the #{@club.name} club", club_path(@club.id), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'This action cannot be undone! Are you sure you want to delete this club?'} %>
  <br>
  <br>
<% end %>
<br>
<% if @club_users %>
  <h4>Edit Member Admin status:</h4>
  <br>
  <% @club_users.each do |cu| %>
    <li>  <%= cu.user.name %> </li>
    <p>Reason for joining: <%= cu.reason %> </p>
    <%= form_for(cu, url: user_club_user_path(cu.user_id))  do |f| %>
      Club Admin?  <%= f.check_box :admin %>
      <br>
      <%= f.submit "Update", class: "btn btn-primary"%>
    <% end %> <br>
      <%= button_to 'Remove this member?', user_club_user_path(cu.user_id), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to Remove this member' } %><br>
  <% end %> 
<% end %>
<br>
<%= link_to '< Back to club page', club_path(params[:id])%>

app/views/clubs/index.html.erb
<br>
<%= show_index_title_conditionally %>
<br><br>
<div class="row row-cols-1 row-cols-md-3"  >
  <% @clubs.each do |c|%>
    <div class="col mb-4">
      <div class="card h-100">
        <% if c.logo.attached? %>
          <%= image_tag c.logo, size: "150x150", alt: "Club Logo", class: "card-img-top"%>
        <%else%>
          <%= image_tag("no_logo.png", size: "200x148", class: "card-img-top", alt: "No logo icon") %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"> <%= link_to c.name, club_path(c.id)%> </h5>
          <p class="card-text"> <%= c.summary.split[0..6].join(' ') %> </p>
          <%#= link_to "Join a club", new_club_club_user_path(@c.id) if session[:user_id].present? %>
        </div>
        <div class="card-footer">
          <small class="text-muted">Created:  <%= c.date_founded.strftime("%d %B %Y") %> </small> <br>
          <small class="text-muted">By: <%= link_to c.user.name, user_path(c.user_id) %> </small> 
        </div>
      </div>
    </div>
  <%end%>
</div>
<!-- 
<br>
<br>
<br>
<h6>DEVELOPER TO DO:</h6>
<p> Add links to join clubs current user isn't a part of or did not created
</p>
<p>
  Add links/buttons to leave club current user is a part of
</p>
Created by: <%#= link_to c.user.name, user_path(c.user_id)%>
-->

app/views/clubs/new.html.erb
<h1>Create a new Club</h1>
<%= render partial: 'layouts/errors', locals: {obj: @club} %>
<%= form_for(@club) do |f| %>
  <label for="club_name"> Club Name</label>
  <%= f.text_field :name, class:"form-control"%>
  <br>
  <label for="club_summary"> In 1 to two sentences, what is the purpose of your club? </label>
  <%= f.text_field :summary, class:"form-control"%>
  <br>
  <label for="club_desctription">In more words, explain how your club came about and how it functions</label>
  <%= f.text_area :description, class:"form-control"%>
  <br>
  <label for="club_date_founded">Date Founded</label>
  <%= f.date_field :date_founded, class:"form-control"%>
  <br>
  <label for="club_logo">Upload Club Logo</label>
  <%= f.file_field :logo %>
  <br>
  <br>
  <%= f.submit "Create Club", class: "btn btn-primary btn-lg"%>
<% end %>

app/views/clubs/show.html.erb
<h1> <%= @club.name %>  </h1>
<br>
<% if !@club_users.exists?(user_id: current_user.id) %>
  <%= link_to "Join This club", new_club_club_user_path(@club.id), class:"btn btn-primary" if session[:user_id].present? %>
  <br>
<%else%>
  <%= button_to 'Leave this club', user_club_user_path(current_user.id), class:"btn btn-secondary" , method: 'delete', data: { confirm: 'Are you sure you want to leave this club?' } %>
<%end%>
<br>
<% if @current_user.id  == @club.user_id || (@club_users.exists?(user_id: current_user.id) && @club_user_user.admin) %>
  <%= link_to "Club Edit Page", edit_club_path(@club.id), class:"btn btn-primary"if session[:user_id].present? %>
<%end%>
<br>
<br>
<% if @club.logo.attached? %>
  <%= image_tag @club.logo, size: "150x150", alt: "Club Logo" %>
<%else%>
  <%= image_tag("no_logo.png", size: "200x148", alt: "No logo icon") %>
<% end %>
<br>
<br>
<b>Summary</b>
<p> <%= @club.summary %> </p>
<b>Description</b>
<p> <%= @club.description %> </p>
<b>Date Created:</b>
<p> <%= @club.date_founded.strftime("%d %B %Y") %> </p>
<b>Creatd By:</b>
<p> <%= link_to @club.user.name, user_path(@club.user.id) %> <small class="text-muted"> Contact: <%=  @club.user.email %> </small></p>
<%if @club_users.length > 0 %>
  <h3>Current Club Admins:</h3>
  <ul>
    <% @club_users.each do |cu|%>
      <%if cu.admin%>
        <li><%= link_to cu.user.name, user_path(cu.user.id)%> <small class="text-muted">Admin.</small> <br>
        </li>
      <%end%>
    <% end %>
  </ul>
  <%= link_to "See all #{@club_users.count} Member(s) and admins of this club!", club_club_users_path(@club.id) %>
<%else%>
  <h3>There are currently no members in this club</h3>
<% end %>
<br>
<br>
<% if !@club_users.exists?(user_id: current_user.id) %>
  <%= link_to "Join This club", new_club_club_user_path(@club.id), class:"btn btn-primary" if session[:user_id].present? %>
<%else%>
  <%= button_to 'Leave this club', user_club_user_path(current_user.id), class:"btn btn-secondary" , method: :delete, data: { confirm: 'Are you sure you want to leave this club?' } %>
<%end%>
<br>
<!-- 
<h6>DEVELOPER TO DO:</h6>
</p>
<p>add social media links (as database column) and  display  in view</p>
<p> Make page look pretty </p>
-->