config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'


  resources :users
  resources :clubs#, only: [:index, :show, :new]

  resources :users do
    resources :clubs
  end
  
  resources :clubs do
    resources :club_users
  end
  # http://127.0.0.1:3000/clubs/1/club_users/new

  resources :users do
    resources :club_users
  end
  # resources :users do
  #   resources :club_users, shallow: true ##shallow: true routing to avoid deep nesting
  # end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :club_users, :dependent => :destroy

  # has_many :clubs, through: :club_users
  has_one_attached :avatar
  has_many :club_memberships, through: :club_users, source: :club, :dependent => :destroy #Clubs they joined
  has_many :club_members, through: :club_users, source: :club, :dependent => :destroy #Clubs they joined
  has_many :clubs, :dependent => :destroy #clubs they created

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: {with: /\A(?<name>[^@\s]+)@(?<domainname>([-a-z0-9]+)\.(?<domain>[a-z]{2,}))\z/i}

  def self.create_by_google_omniauth(auth)
    self.find_or_create_by(email: auth[:info][:email]) do |u|
      u.name = auth["info"]["name"]
      u.password = SecureRandom.hex
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to user_path(current_user.id) if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
    @club_users = ClubUser.where(user_id: @user.id)
    # byebug
    redirect_to "/" if !@user
  end

  def index
    redirect_if_not_logged_in
    @user = User.all
    # redirect_to '/' if !@user
  end

  def edit
    redirect_if_not_authorized
    @user = User.find_by_id(params[:id])
  end

  def update
    redirect_if_not_authorized
    @user = User.find_by(id: params[:id])
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, session[:user_id], :avatar)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @user} %>
<h4>Update Your Profile Information</h4> <br>
<%= form_for(@user) do |f| %>
  <div class="form-group">
    <label for="user_name">Name</label>
    <%= f.text_field :name, class:"form-control"%> <br>
    <label for="user_email">Email</label>
    <%= f.email_field :email, class:"form-control"%> <br>
    <label for="user_avatar">Profile pic</label> <br>
    <%= f.file_field :avatar, class:"form-control" %>
  </div> <br>
  <%= f.submit "Update your info", class: "btn btn-primary"%>
<% end %>
<br><br>
<%= link_to '< Back to your profile page', user_path(params[:id])%>

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @user} %>
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
<div class="form-group">
    <label for="user_name">Name</label>
    <%= f.text_field :name, class:"form-control",  placeholder:"Name" %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="user_email">Email</label>
      <%= f.email_field :email, class:"form-control", placeholder: "Email" %>
    </div>
    <div class="form-group col-md-6">
      <label for="user_password">Password</label>
      <%= f.password_field :password, class:"form-control", placeholder: "Password"%>
    </div><br> <br>
    <label for="user_avatar">Profile pic</label> <br>
    <%= f.file_field :avatar, class:"form-control" %>

  </div>
  
</div>
<%= f.submit "Signup", class: "btn btn-primary"%>
<% end %>
<br>
<%= link_to "back to welcome page", '/' if !session[:user_id].present? %>
OR
<%= link_to "Login", login_path %>
<br>

app/views/users/show.html.erb
<% if @user == current_user%>
  <h4>Hello <%= @user.name %>! This is your profile </h4>
  <br>
<%else%>
  <h4> <%= @user.name %>'s Profile </h4>
  <br>
<%end%>
  <%= link_to "Edit your profile", edit_user_path(@user.id) if authorize_user(@user.id) %>
<br><br>
  <% if @user.avatar.attached? %>
  <%= image_tag @user.avatar, size: "150x150", alt: "Profile image of student" %> 
    <%else%>
    <%= image_tag("no_profile_image.png", size: "200x148", alt: "No profile image icon") %> 
  <% end %>
  <br><br>
<small class="text-muted"> Contact: <%=  @user.email %> </small>
  
  
<!-- .representation(resize_to_limit: [100, 100]).processed.url -->
<% if @user.clubs.length > 0%>
<br><br>
  <% if @user == current_user%>
    <h4>Here are all  the  clubs you have  created:</h4>
  <%else%>
  <h4>Here are all  the  clubs <%= @user.name %> created:</h4>
  <%end%>
  <% @user.clubs.each do |uc|%>
    <p><%= link_to uc.name, club_path(uc.id) %> </p>
  <%end%>
<%end%>
<br>
<%#= DateTime.new(2001,2,3,4,5,6).strftime("%D %r") %>
<% if @club_users.any?%>
  
  <h5>Currently a Member of:</h5>
  <ul>
    <% @club_users.each do |cu|%>
      <li><%= link_to cu.club.name, club_path(cu.club.id)%> <small class="text-muted"> Created by: <%= link_to cu.club.user.name, user_path(cu.club.user.id) %> </small>  </li>
    <% end %>
  </ul>
<% else%>
<br> <br>
  <h5>You are not currently a member of any clubs</h5>
  <br><br>

  <%= link_to "Create a Club", new_club_url if logged_in? %> |
  <%= link_to "Join an existing club", clubs_path if session[:user_id].present?  %>

<%end%>
<!-- 
<h6>TO DO:</h6>
<p> Show clubs this user created with button to delete each club </p>
<p> Show clubs this user joined with button to leave each club
</p>
<p>
  Add links/buttons to leave club if current user is a member
</p>
<p> Add short bio (as database column) and display  in view </p>
<p>add social media links (as database column) and  display  in view</p>
<p> Make page look pretty </p>
<p>  </p>
-->