config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'


  resources :users
  resources :clubs#, only: [:index, :show, :new]

  resources :users do
    resources :clubs
  end
  
  resources :clubs do
    resources :club_users
  end
  # http://127.0.0.1:3000/clubs/1/club_users/new

  resources :users do
    resources :club_users
  end
  # resources :users do
  #   resources :club_users, shallow: true ##shallow: true routing to avoid deep nesting
  # end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <b><%= pluralize(obj.errors.count, "error") %> prohibited this from being saved:</b>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li class= "text-danger"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<% if logged_in? %>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <!-- Navbar content -->
    <div class="container">
      <h5><%= link_to "My Profile Page", user_path(session[:user_id]), class: "nav-link text-white", style: "text-decoration: underline;" if session[:user_id].present? %></h5>
      <!-- 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     -->
    </div>
    <!-- 
    <div class="collapse navbar-collapse" id="navbarNav">
    -->
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Create a Club", new_club_url, class: "nav-link" if logged_in? %>
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
      </li>
      <li class="nav-item">
        <%= link_to "All clubs", clubs_path, class: "nav-link" if logged_in?  %>
      </li>
      <li class="nav-item">
        <%= button_to "Log Out", logout_path, method: :delete, class: "nav-link btn btn-primary" if logged_in? %>
      </li>
    </ul>
    <!-- </div> -->
  </nav>
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Navbar content -->
    <div class="container">
      <h4><%= link_to "Home", '/', class: "nav-link text-white" %></h4>
      <!-- 
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      -->
    </div>
    <!-- 
    <div class="collapse navbar-collapse" id="navbarNav">
    -->
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Login", login_path, class: "nav-link" %>
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
      </li>
      <li class="nav-item">
        <%= link_to "Signup", signup_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= button_to "Sign in or Signup with google", '/auth/google_oauth2',  method: :post, class: "nav-link btn btn-primary" %>
      </li>
    </ul>
    <!-- 
    </div>
     -->
  </nav>
<%end%>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClubRegistration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: 'layouts/nav' %> <br>
     <br>
    <div class="container">
      <div class="row d-flex justify-content-center">
        <!--Grid column-->
        <div class="col-md-6">
          <%= yield %>
          <br>
          <br>
          <br>
          <span> <%= "Currently Logged in: "+ current_user.name if logged_in? %> </span>
          <br>
          <br>
          <br>
        </div>
      </div>
    </div>
  </body>
</html>